### ISSUE TITLE
grasp-squery fails when used with acorn-object-spread

### ISSUE THREAD

**Issue by vidoss** [gkz/grasp-squery#5]
grasp-squery fails when used with acorn-object-spread.

```
TypeError: Cannot read property 'start' of undefined
    at node_modules/grasp-squery/lib/common.js:17:40
    at visitPre (node_modules/grasp-squery/lib/common.js:36:5)
    at visitPre (node_modules/grasp-squery/lib/common.js:49:9)
    at visitPre (node_modules/grasp-squery/lib/common.js:59:11)
    at visitPre (node_modules/grasp-squery/lib/common.js:59:11)
    at new Cache (node_modules/grasp-squery/lib/common.js:10:5)
    at Object.queryParsed (node_modules/grasp-squery/lib/index.js:9:64)
    at search (node_modules/grasp/lib/index.js:216:29)
    at run (node_modules/grasp/lib/index.js:397:7)
```

Code to reproduce attached.
[squery_fail.txt](https://github.com/gkz/grasp-squery/files/972507/squery_fail.txt)

**Comment by junyo** [comment]
+1

**Comment by adros** [comment]
+1
